### ISSUE TITLE
请求大神答复一个疑问

### ISSUE THREAD

**Issue by mhlee0514** [diwu/RunLoopWorkDistribution#7]
为什么我认为，这个不是每次RunLoop结束前执行一次任务，而且在一次RunLoop结束的前下执行了所有在tasks中的任务？
如果只执行一次的话，那么RunLoop休眠，页面保持静止，应该只加载一张图的啊。

    while (result == NO && runLoopWorkDistribution.tasks.count) {
        DWURunLoopWorkDistributionUnit unit  = runLoopWorkDistribution.tasks.firstObject;
        result = unit();
        [runLoopWorkDistribution.tasks removeObjectAtIndex:0];
        [runLoopWorkDistribution.tasksKeys removeObjectAtIndex:0];
    }

这个不是一次执行完的吗？

**Comment by Jerry0523** [comment]
因为在DWURunLoopWorkDistribution.m 50:8 的地方，作者起了一个定时器。。。。所以runloop永远不会休眠。。

**Comment by mhlee0514** [comment]
非常感谢。阅读源码不仔细，向大佬学习！
